import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            All Responses to CSE excercise found under&nbsp;
            <code className={styles.code}>pages/responses/</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
        <p>Hello, I'm Holden. I'm a software developer and writer (Poetry). You can contact me on{' '} 
          <a href="https://www.linkedin.com/in/holden-altaffer-609033ab/">Linkedin</a>.
        </p>
        </div>

        <div className={styles.grid}>
          <a
            href="/responses/one"
            className={styles.card}
          >
            <h2 className={inter.className}>
              ONE <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
            What do you want to learn or do more of at work?
            </p>
          </a>

          <a
            href="/responses/two"
            className={styles.card}
          >
            <h2 className={inter.className}>
              TWO <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
            Describe how you solved a challenge?
            </p>
          </a>

          <a
            href="/responses/three"
            className={styles.card}
          >
            <h2 className={inter.className}>
              THREE <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
            How would you compare Next.js with another framework?
            </p>
          </a>

          <a
            href="/responses/four"
            className={styles.card}
          >
            <h2 className={inter.className}>
              FOUR <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
            When would you use Edge Functions, Serverless Functions, or Edge
Middleware with Vercel?
            </p>
          </a>

          <a
            href="/responses/five"
            className={styles.card}
          >
            <h2 className={inter.className}>
              FIVE <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
            Build issue first response.
            </p>
          </a>

          <a
            href="/responses/six"
            className={styles.card}
          >
            <h2 className={inter.className}>
              SIX <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
            Most common customer issues.
            </p>
          </a>

          <a
            href="/responses/seven"
            className={styles.card}
          >
            <h2 className={inter.className}>
              SEVEN <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
            How could we improve or alter this familiarization exercise?
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
